apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-service
  template:
    metadata:
      labels:
        app: chatbot-service
    spec:
      containers:
        - name: chatbot-service
          image: enset/chatbot-service:latest
          env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://discovery-service:8761/eureka
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: "false"
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  type: ClusterIP
  selector:
    app: chatbot-service
  ports:
    - port: 8090
      targetPort: 8090
